---
apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: ptsak-alerts
  namespace: default
  labels:
    team: ptsak
spec:
  receivers:
    slack:
      channel: "#gsak_kafka_til_dvh"
  alerts:
    - alert: applikasjon nede
      expr: up{app="pt-sak-consumer", job="kubernetes-pods"} == 0
      for: 2m
      description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
      action: "Sjekk events via `kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}`, og logger via `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}`"
