apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pt-sak-consumer
  namespace: default
  labels:
    team: ptsak
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2
  vault:
    enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  liveness:
    path: /
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /
  ingresses:
    - https://pt-sak-consumer.nais.{{ domain }}
